import { Inter } from "next/font/google";
import "@/style/globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Popup from "@/components/Popup/Popup";
import ReduxProvider from "@/redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Semih Şahinoğlu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <ReduxProvider>
          <Popup />
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
